language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sygrimace/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sygrimace/docker-react npm run test -- --coverage

deploy:
  provider: releases
  api_key: "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"
  file_glob: true
  file: build/**/*
  skip_cleanup: true
  on:
    tags: true